language: node_js
node_js:
- "0.10"
- "0.11"
- "0.12"
sudo: false
addons:
  code_climate:
    repo_token:
      secure: "<INSERT TOKEN HERE>"
after_script:
  - npm install -g codeclimate-test-reporter
  - cat coverage/lcov.info | codeclimate
